services:
  - type: web
    name: personalwebsite
    env: static
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    staticPublishPath: ./build/web
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /*.js
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /*.wasm
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /canvaskit/*
        name: Cache-Control
        value: public, max-age=31536000, immutable

